### ISSUE TITLE
GNU/Linux Support

### ISSUE THREAD

**Issue by Katiausha** [Babyhamsta/Aimmy#103]
Aimmy GUI
Seems to work well with [Wine GE](https://github.com/GloriousEggroll/wine-ge-custom/releases) along side with [Vinegar](https://github.com/vinegarhq/vinegar), although I forget to setup properly the fonts. **Normal Wine (8.x.x) doesn't open Aimmy.**

Tweaks: Manual DotNet installation

Aimmy overall functionalities available
Bad, didn't worked properly, with a severe cpu leak ~90% (4.20 ghz).

Game tested: [Phantom Forces](https://www.roblox.com/games/292439477/Phantom-Forces-PC)

**Not willing to port Aimmy for Linux / Mac system** too busy due school, writing this for others Wine - Roblox users who may attempt to test Aimmy.

![2023-12-02-234516_679x540_scrot](https://github.com/Babyhamsta/Aimmy/assets/103280689/7866cce0-5a5e-4e53-a394-29052138d1f9)

**Comment by Euro-pol** [comment]
thanks

**Comment by Babyhamsta** [comment]
Aimmy is done with WPF which should support Linux natively. The other thing I am not sure if it supports is the dlls included with Aimmy such as the Onnx Backend or DirectML backend.

**Comment by luckyez** [comment]
afaik WPF and DirectML has no support for GNU+Linux
