### ISSUE TITLE
SDK Resolver Failure When Opening in VS 22

### ISSUE THREAD

**Issue by Fr0go1** [Babyhamsta/Aimmy#105]
https://discord.com/channels/1172932293288013936/1181175591840526336

> D:\AI-image\Aimmy\AimmyWPF\AimmyWPF.csproj : error  : SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk". Exception: "Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestFormatException: Expected StartObject token at offset 1
>    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestReader.ThrowUnexpectedTokenException(Utf8JsonStreamReader& reader, JsonToken expected)
>    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestReader.ReadWorkloadManifest(String id, String manifestPath, LocalizationCatalog localizationCatalog, Utf8JsonStreamReader& reader)
>    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestReader.ReadWorkloadManifest(String manifestId, Stream manifestStream, Stream localizationStream, String manifestPath)
>    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.LoadManifestsFromProvider(IWorkloadManifestProvider manifestProvider)
>    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion, String userProfileDir)
>    at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion, String userProfileDir, String globalJsonPath)
>    at Microsoft.DotNet.MSBuildSdkResolver.DotNetMSBuildSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext context, SdkResultFactory factory)
>    at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.TryResolveSdkUsingSpecifiedResolvers(IList`1 resolvers, Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio, SdkResult& sdkResult, IEnumerable`1& errors, IEnumerable`1& warnings)""  D:\AI-image\Aimmy\AimmyWPF\AimmyWPF.csproj

this is the error

**Comment by Babyhamsta** [comment]
We don't offer support for VS errors.
