### ISSUE TITLE
isnt aiming at all

### ISSUE THREAD

**Issue by eutyteam** [Babyhamsta/Aimmy#117]
it just doesnt move cursor or anything as old v1.3 version, i choiced models, i tried enabling aim alligner always on, i tried doing ai confidence to 1, still the cursor at same place, i tried every model from downloable list, still the same

**Comment by xXFinionXx** [comment]
Its the same for me...

**Comment by eutyteam** [comment]
> Its the same for me...

yeah, no point in using the new version then

**Comment by Babyhamsta** [comment]
Potentially due to the input driver, please use v1.4.6 ->
