### ISSUE TITLE
aiming does nothing and goes super laggy

### ISSUE THREAD

**Issue by NooobLorod** [Babyhamsta/Aimmy#121]
doesnt work at all and tried all the models and when pressing the key goes super laggy

**Comment by Exotikcheatt** [comment]
i try into fortnite / apex and not work for me ( i build the project ) =(
No aim / No Trigger

**Comment by Babyhamsta** [comment]
Potentially a PC performance issue which we cannot fix. It takes a lot to run AI detections every 0.01-0.05 seconds.
You can try the newest version to see if it helps any.
