### ISSUE TITLE
Model Error

### ISSUE THREAD

**Issue by ThanhMinecraftVN123** [Babyhamsta/Aimmy#1283]
The error like this:
![Capture](https://github.com/Babyhamsta/Aimmy/assets/83948193/faaff59c-9bed-4aaa-af9e-1a1a41d7ab3d)
pls help me

**Comment by gostino499** [comment]
i have the same issue its using cpu only. pc specs: i5-9400F RTX 3060 TI

**Comment by Leozgu** [comment]
Me too

**Comment by Leozgu** [comment]
Problem solved, you just need to build it as x64 instead of any CPU
