### ISSUE TITLE
How to full uninstall?

### ISSUE THREAD

**Issue by ReallReaper** [Babyhamsta/Aimmy#1285]
I was banned from several games even though I deleted all the aimmy files on my PC, I need to know how to do a full uninstall of this

**Comment by l3afai** [comment]
its too late, once you got aimmy, you cant get back, it knows u had aimmy beacuse it fingerprints your pc and says "HWID DAJOIWDNDAONDO HAS AIMMY" then bans you.

**Comment by whoswhip** [comment]
To do a full un-install first obviously delete the aimmy folder then head into sys32 then into drivers and check for the mouse.sys and the keyboard.sys if those are there thats the driver aimmy uses. Delete those then head into "C:\Users\username\AppData\Local\Babyhamsta" and delete the Babyhamsta file, that should be about it. for more help you can join our discord, discord.gg/aimmy
