### ISSUE TITLE
runnig the builded exe of the source 1.5.2 will cause it to use the cpu instead of the gpu 

### ISSUE THREAD

**Issue by gostino499** [Babyhamsta/Aimmy#1292]
![Screenshot 2024-01-01 102430](https://github.com/Babyhamsta/Aimmy/assets/155027833/b6f5382e-490e-4433-b6f2-54d32026c6fa)

**Comment by gostino499** [comment]
1.5.2 BETA work fine but source version doesnt

**Comment by MarsQQ** [comment]
@gostino499 Build it as x64 instead of Any CPU and see if it works. Good luck!
