### ISSUE TITLE
Possible detection by roblox (As of 05/01/2024)

### ISSUE THREAD

**Issue by hl2jeep** [Babyhamsta/Aimmy#1297]
noticed this earlier today, if aimmy is launched with roblox running, it will after about 30 seconds crash and delete the name scrambled AimmyWPF.exe. i have confirmed this to not be an antivirus issue, as it only occurs when roblox is running, in my case no ban or warning was issued.

**Comment by furdiburd** [comment]
rename the .exe may help

**Comment by hl2jeep** [comment]
The launcher does that automatically, renaming the exe would not change
anything

**Comment by whoswhip** [comment]
this could be just a launcher issue because it seems you are using the launcher because of the scrambling, so maybe just try aimmywpf

**Comment by Babyhamsta** [comment]
This is 100% not a ROBLOX issue, ROBLOX wouldn't delete an exe from your computer. This sounds like Windows Defender or something else is deleting it.
