### ISSUE TITLE
it doesnt work when i am in fullscreen in game

### ISSUE THREAD

**Issue by johnjakston** [Babyhamsta/Aimmy#1299]
aimmy doesnt work when i am in fullscreen, and the FOV circle wont show up on screen when fullscreened. I am playing APEX legends and the finals, I have to windowed the resolution so it will work. Is there any way it will work on fullscreen in game?

**Comment by whoswhip** [comment]
Sorry but thats just how the fov system works it requires you to be in borderless/windowed fullscreen
