### ISSUE TITLE
Can fix multi-player jitter？

### ISSUE THREAD

**Issue by luke-rabbit** [Babyhamsta/Aimmy#130]
Can fix multi-player jitter？

**Comment by MarsQQ** [comment]
Explain more?

**Comment by luke-rabbit** [comment]
> Explain more?

If you encounter many people, the Aim Aligning will jitter.

**Comment by Babyhamsta** [comment]
I mean we add fake jitter to aim, in update 1.5.0 the jitter will be adjustable. Any other issues with aim are most likely a config / pc performance issue.
