### ISSUE TITLE
Any one have valorant model?

### ISSUE THREAD

**Issue by Zeroxsho** [Babyhamsta/Aimmy#1301]
Any one have valorant model?

**Comment by Donkey69-69** [comment]
There is a Vaolront Model don't use Aimmy for valoront or anything with easy-anti cheat cuz it can detect your aim movement and that stuff

**Comment by Zeroxsho** [comment]
its not detectable but where u say you found valorant model?

**Comment by MarsQQ** [comment]
aimmy is detectable on valorant so there is no valorant models

**Comment by waxnet** [comment]
surely not detectable :clueless:

**Comment by NeedlessPage819** [comment]
> surely a free aimbot is undetected on valorant

its an ai aimbot so it doesnt acces the memory of the game it should not be detectable
