### ISSUE TITLE
It now detects as a virus ?

### ISSUE THREAD

**Issue by ShavoyMartin** [Babyhamsta/Aimmy#1305]
i am an early aimmy user and strangely enough when i scanned aimmy 1.1, it didnt detect it as a virus even outside of exclusion folders... now it does.

**Comment by svawes** [comment]
Only on Games with eac Like Fortnite or Valaront Download The new Version of Aimmy

**Comment by Babyhamsta** [comment]
Aimmy is not a virus, you are more than welcome to build it yourself.

**Comment by hjyuh** [comment]
its probably because of the aimmywpf.dll, from my knowledge. I don't know what It does. (i do but slightly) and how do i build it myself
