### ISSUE TITLE
how do I build Aimmy.

### ISSUE THREAD

**Issue by hjyuh** [Babyhamsta/Aimmy#1316]
do to my intelligence being comparable to a 4 year old. I'm genially dumbfounded on how to build aimmy.

**Comment by waxnet** [comment]
You need visual studio to build it, when you have it installed just open "AimmyWPF.sln" and build it.
If you dont know how to do that just search for a tutorial online.

**Comment by hjyuh** [comment]
i did it, idk why i kept this post up. but tysm

**Comment by waxnet** [comment]
no problem bro
