### ISSUE TITLE
Detected on The Finals game.

### ISSUE THREAD

**Issue by Cypher212** [Babyhamsta/Aimmy#1318]
Everything was working fine for weeks if not months, but as of today's update, Aimmy is detected as a disallowed tool detected by their system. Just wanted to pass the news out there!

**Comment by waxnet** [comment]
I mean its just not going to work on very big games in general tbh

**Comment by Juanchomax** [comment]
Right, any work around on this one? any updates patch by the creator?

**Comment by waxnet** [comment]
> Right, any work around on this one? any updates patch by the creator?

i dont think there are any work arounds, stuff like this gets detected all the time and would require a dedicated bypass
