### ISSUE TITLE
Detected on The APEX.

### ISSUE THREAD

**Issue by ByZain** [Babyhamsta/Aimmy#1322]

**Comment by ERROR200013** [comment]
Games that can detect Aimmy:
                   Fortnite
                  Valorant
              Apex Legends
And anti-cheats:
          EAC (Easy Anti Cheat)
              BE (Battle Eye)
You can cheat in any games except these.

**Comment by navyanayub** [comment]
Will it work on PUBG mobile running on an emulator? or can it run on android? is it possible I mean?
