### ISSUE TITLE
Hopefully, it will be possible to implement multiple classes

### ISSUE THREAD

**Issue by PTA00** [Babyhamsta/Aimmy#1339]
I have two classes called head and body
Preference is given to one class over another

**Comment by rhjn13** [comment]
With a 0.2 sight it's harder to hit the head.  It all depends on the weapon, what it is for.  If you cut into the body and the recoil just doesn’t have time to adjust to the head

**Comment by Babyhamsta** [comment]
Unless you want to go through and remake a model for a game with each body part highlighted then no. We don't have that support here nor do we plan on adding it here. You can use offsets to try and achieve the same effect.

**Comment by PTA00** [comment]
> 除非你想通过并重新制作一个游戏模型，并突出显示每个身体部位，否则不行。我们在这里没有这种支持，也不打算在这里添加它。您可以使用偏移量来尝试实现相同的效果。

thank you for the response.
I tried to query the second class when I couldn't get the first class. Here is my code, very rudimentary.


```
var filteredIndices = Enumerable.Range(0, NUM_DETECTIONS)
                        .AsParallel()
                        .Where(i => outputTensor[0, 5, i] >= ConfidenceThreshold)
                        .ToList();
if (!filteredIndices.Any())
{
    filteredIndices = Enumerable.Range(0, NUM_DETECTIONS)
                        .AsParallel()
                        .Where(i => outputTensor[0, 4, i] >= ConfidenceThreshold)
                        .ToList();
}
```
