### ISSUE TITLE
I tried to modify the program to detect simultaneous left and right mouse button press, but failed

### ISSUE THREAD

**Issue by PTA00** [Babyhamsta/Aimmy#1340]
globalmousekeyhook does not seem to support detecting mousekey combinations

**Comment by Babyhamsta** [comment]
Aimmy V2 allows for multiple keybinds where V1.5 didn't have that support. V2 should be out shortly!

**Comment by PTA00** [comment]
> Aimmy V2 允许在 V1.5 不支持的情况下进行多个键绑定。V2 应该很快就会推出！

thank you for the response.
I think I understand now.I should have set a listener for each mouse button.
Then the state of the other key is judged in the action of one of the keys.

Understanding your code takes some effort.Can you briefly describe the logic of the aiming algorithm?
