### ISSUE TITLE
.net

### ISSUE THREAD

**Issue by rigby345345** [Babyhamsta/Aimmy#1343]
When it opens it says something about "Download .net to run aimmyWPF" and when i download nothing happens and still doesnt open

**Comment by wrtrteyteey23ee** [comment]
is it installed?

**Comment by rigby345345** [comment]
wdym

**Comment by rigby345345** [comment]
the thing is it says downloaded but still doesnt open

**Comment by rigby345345** [comment]
wait nvm i had to open .net then install it

**Comment by rigby345345** [comment]
it works now
