### ISSUE TITLE
output shape 1x6x8400 does not match the expected shape of 1x5x8400

### ISSUE THREAD

**Issue by kefti** [Babyhamsta/Aimmy#1348]
![image](https://github.com/Babyhamsta/Aimmy/assets/159721479/1e1df29d-ad69-4f87-85da-f063d90887be)
output shape 1x6x8400 does not match the expected shape of 1x5x8400

**Comment by PTA00** [comment]
You just need to change the code.

**Comment by sam23225** [comment]
Can you please explain it more easily?

**Comment by sam23225** [comment]
> You just need to change the code.

Can you explain in more detail?
