### ISSUE TITLE
Unable to extract Aimmy v2

### ISSUE THREAD

**Issue by bageler1** [Babyhamsta/Aimmy#1354]
![image](https://github.com/Babyhamsta/Aimmy/assets/148931432/c7c28ddd-bdc4-4891-965e-8aa58f8757f0)
Does the same with all other items.
When skipping unextractable items I am left with the second image
![image](https://github.com/Babyhamsta/Aimmy/assets/148931432/5f6ff7e0-6a9f-436a-966a-c029e9c030d8)

**Comment by ammystic** [comment]
I Found out how to fix, extract it with winrar
