### ISSUE TITLE
HOW

### ISSUE THREAD

**Issue by yeh111w** [Babyhamsta/Aimmy#1360]
I use yolo train a model and put it in to the model folder
but not work

![image](https://github.com/Babyhamsta/Aimmy/assets/139565794/2e4369b0-bf32-4245-825d-dac60725b5bf)

**Comment by zoeywowy** [comment]
I am having the same issue

**Comment by zoeywowy** [comment]
I found this closed case of this particular issue and have since fixed the problem!

[https://github.com/Babyhamsta/Aimmy/issues/1328](url)

> This problem occurs when you have more than one classes defined in your **coco128.yaml** dataset(or from Babyhamstas tutorial he named it **CustomCharacterPath_Universal.yaml**) resulting in the shape outputting incorrectly when exporting your model.
