### ISSUE TITLE
Apex Legends Detected ?

### ISSUE THREAD

**Issue by abdo494** [Babyhamsta/Aimmy#1362]
Hey guys does apex legends detected ?

**Comment by Alex-test-mod** [comment]
yes 
https://github.com/Babyhamsta/Aimmy/commit/24ca98473a1576b7d115f76b005cd803239e344d

**Comment by Alex-test-mod** [comment]
good for you (;

**Comment by abdo494** [comment]
> good for you (;

are you really sure ?
