### ISSUE TITLE
Have you considered providing multilingual support?

### ISSUE THREAD

**Issue by hxy310** [Babyhamsta/Aimmy#1369]
Have you considered providing multilingual support?

**Comment by whoswhip** [comment]
I believe they have before, but not only is it annoying to implement they would also need to find people to translate from english to whatever language that they are attempting to add

**Comment by hxy310** [comment]
UI interface can help with translation

**Comment by TaylorIsBlue** [comment]
If you're willing to give any translations for us at the moment we may think about it :)

**Comment by MelvinSGjr** [comment]
> If you're willing to give any translations for us at the moment we may think about it :)

you can use ChatGPT for translating something (better to use Microsoft Copilot) or you can use Deepl
