### ISSUE TITLE
Constant crashing

### ISSUE THREAD

**Issue by mortezaghafoori** [Babyhamsta/Aimmy#1371]
Hi, I had no problems using v1 but when I upgraded to v2, Anything I do crashes Aimmy. I completely deleted v1 and downloaded a fresh v2 and the problem is still there. What to do?

**Comment by ccroic** [comment]
V2 Has a lot of bugs, like runtime crashing, crashing when downloading, and etc. Please use 1.5.2 or above, the developer hasn't fixed that bug yet.

**Comment by mortezaghafoori** [comment]
Sad, because V2 performance is really much better

**Comment by Babyhamsta** [comment]
Please try 2.1.0, a lot of bugs should be fixed.

**Comment by skibidihackertoilet** [comment]
i try to use aimmy but in roblox when i activate my aimbot it crashes

**Comment by klzunqrbx-sketch** [comment]
I HAVE THE SAME BUT MY ISSUE IS WHEN I CLICK THE MODEL IT WONT LET ME ITS CRASHING MY COMPUTER AND IT EXIT IN ITS OWN PLS FIX THIS
