### ISSUE TITLE
ARDUINO AIMBOT FORTNITE 

### ISSUE THREAD

**Issue by isvktt** [Babyhamsta/Aimmy#1374]
Hi guys, I see that many people are wanting to use it in Fortnite and are having problems, I found this video on a forum where the coder uses aim on Arduino for Fortnite, maybe it can help you!
https://www.youtube.com/watch?v=v7I8__L_4No

**Comment by whoswhip** [comment]
I believe they don't have the budget to get an arduino + host shield as of now, there is a fork that uses arduino just not with a host shield btw.
https://github.com/Seconb/Aimmy-Arduino-Edition

**Comment by TaylorIsBlue** [comment]
This is a feature we believe may come in the feature - but not right now.
