### ISSUE TITLE
Aimmy V2 doesn't gather data while playing

### ISSUE THREAD

**Issue by Matt0698** [Babyhamsta/Aimmy#1376]
Aimmy V2 stopped taking screenshots when I enabled the "Gather images while playing". I can see it's trying to, as I deleted the images folder and it creates it again, but no images is being taken. I had it working before but it suddenly stopped. I wanna try the auto labelling as it takes hours labelling thousands of images. It still works on version 1.5.2. Anyone else has this problem?

**Comment by Babyhamsta** [comment]
It will not auto capture if you have it constantly on, that was a change we made in 2.0 due to the large amount of photos it would take.
