### ISSUE TITLE
Detected in Overwatch 2?

### ISSUE THREAD

**Issue by mortezaghafoori** [Babyhamsta/Aimmy#1377]
I just figured out that the AI doesn't work in Overwatch 2. If I load into a practice range, the AI works perfectly fine with great performance but as soon as I join a quick match, it stops working and I have to restart the whole PC for it to work again.
Any ideas?

**Comment by abdo494** [comment]
No

**Comment by Babyhamsta** [comment]
It may be that they disable any calls to Mouse_event, try one of the other movement techniques.
