### ISSUE TITLE
Aimmylauncher extracting issue

### ISSUE THREAD

**Issue by Wolf22g** [Babyhamsta/Aimmy#1381]
Tried to extract the "AimmyLauncher" file in the V2 download and got the error message that the extraction could not be completed without any further information. Restart did not change anything 
![Screenshot 2024-03-16 161848](https://github.com/Babyhamsta/Aimmy/assets/163693067/c1b9a852-1ae7-4f39-9b57-859c825ac902)
![Screenshot 2024-03-16 161805](https://github.com/Babyhamsta/Aimmy/assets/163693067/7bdce65a-e311-4caf-9f30-6379a6c8955b)

**Comment by Areeb5146** [comment]
you need to install 7 zip then right click the downloaded zip and go to 7 zip option and then press extract, i had same issue but this solved

**Comment by rockboy612** [comment]
> you need to install 7 zip then right click the downloaded zip and go to 7 zip option and then press extract, i had same issue but this solved

how do you do that?

**Comment by Babyhamsta** [comment]
Should be fixed with 2.1.0, it was due to use using a different compression than normal.
