### ISSUE TITLE
Aimmy labels incompatible with Make Sense

### ISSUE THREAD

**Issue by RealCalumPlays** [Babyhamsta/Aimmy#1384]
If this is due to how Make Sense works then close this but it seems that the format of labels that Aimmy is using is not compatible with Make Sense.

This seems to be due to some points being negative values as if I flip them to positive values they import (not correctly but they do import)

**Comment by Alex-test-mod** [comment]
lghub_installer 2021.10.8013

**Comment by RealCalumPlays** [comment]
Huh?!

**Comment by Babyhamsta** [comment]
We have had some issues with it putting incorrect screen cords. We'll look into fixing it soon.

**Comment by RealCalumPlays** [comment]
Thats fine. I just wanted to use Make Sense for refining the annotations.

**Comment by TaylorIsBlue** [comment]
This is fixed in the upcoming update
