### ISSUE TITLE
The most important thing is not to get banned

### ISSUE THREAD

**Issue by MelvinMod** [Babyhamsta/Aimmy#1388]
I want this aimbot to record the movement of my mouse and repeat (any moment and any of my mouse movement), and also, I want a very smooth aimbot, but what I first said is important, so that really do not get banned. Also you forget about fix Trigget Bot that shoots whenever he wants (not on the button I assigned) and so on that in Aimmy V1 is existed (but not in the Aimmz V2)

**Comment by abdo494** [comment]
Hi bro should i be worried about using the old version like v1.5.1 because i use it and is pretty cool for me this version, im playing apex legends btw.

**Comment by abdo494** [comment]
Hi bro, should i be worried to use old version like v1.5.1 , because i use it for now on apex legends are there any risks that i should avoid for now?
