### ISSUE TITLE
Wrong version | No models

### ISSUE THREAD

**Issue by kirill-21** [Babyhamsta/Aimmy#1389]
![image](https://github.com/Babyhamsta/Aimmy/assets/63228361/d1d0503b-83ad-4f06-9938-66b5e6f0862f)
![image](https://github.com/Babyhamsta/Aimmy/assets/63228361/d5605daa-6841-4693-88cc-c5d97c8f3161)

For some reason even when i download 2.1.0 from git it still launches 2.0.0 and models tab is empty
![image](https://github.com/Babyhamsta/Aimmy/assets/63228361/a407839d-da5b-4477-89dc-85dec8728968)

**Comment by kirill-21** [comment]
And update button in settings tab just infinitely downloads the update

**Comment by Babyhamsta** [comment]
May of forgotten to update the version number, we'll look at fixing it upon the next update. It should be the newest version.

**Comment by kirill-21** [comment]
> May of forgotten to update the version number, we'll look at fixing it upon the next update. It should be the newest version.

Problem is not in the version but in the fact that uploaded version is not the latest, there are no models there, test by yourself

**Comment by TaylorIsBlue** [comment]
This is fixed in the upcoming update
