### ISSUE TITLE
immediately crashing

### ISSUE THREAD

**Issue by russian220** [Babyhamsta/Aimmy#1395]
immediately after the message *load model phantomforcechamsta* aimmy crashes

**Comment by q0zas** [comment]
same for me its so annoying. i havent been able to use aimmy for weeks because of this, but now its showing the message "phantomforcehamsta" and then crashes.

**Comment by russian220** [comment]
Well, at least I'm not like that here

**Comment by Babyhamsta** [comment]
Have you fully extracted Aimmy before running it? Ensure that both the DirectML.dll and OnnxRuntime.dll are with the exe as well.

**Comment by q0zas** [comment]
Yup, both of those files are there.

**Comment by TooManyFactoryResets** [comment]
Do you have 7.0 .NET installed on your computer?
