### ISSUE TITLE
Help on this

### ISSUE THREAD

**Issue by DelikadongPako** [Babyhamsta/Aimmy#1407]
Output shape 1x13x8400 does not match the expected shape of 1x5x8400.This model will not work with Aimmy, please use an ONNX V8 model.

**Comment by Babyhamsta** [comment]
OnnxV8 requires 1,5,8400 which is what we require. We do want to potentially automate the handling of future models by automating the handling of sizes but currently we only support the one.

If you could attach your model here I can inspect it. Ensure you are converting a YOLOv8 model to Onnx.

It seems like your output has 13 and not 5. The output should be x, y, width, height, confidence.
You can also inspect the element on [Netron](https://netron.app).
