### ISSUE TITLE
Where can I change mouse movement method to my own method?

### ISSUE THREAD

**Issue by pigking0126** [Babyhamsta/Aimmy#1408]
Where can I change mouse movement method to my own method?
C# makes me headache.
I tried search "ddxoft.dll" and "lghub" but couldn't find anything.

**Comment by Babyhamsta** [comment]
Ensure you have the V2 Source, you can find it in the V2 branch on this Github.

https://github.com/Babyhamsta/Aimmy/tree/Aimmy-V2/Aimmy2/MouseMovementLibraries
