### ISSUE TITLE
what is this

### ISSUE THREAD

**Issue by rkdalswp** [Babyhamsta/Aimmy#1409]
![image](https://github.com/Babyhamsta/Aimmy/assets/169869389/80a7f0b8-186c-4209-a71e-e8dca0b1196b)
what is this?

**Comment by Tung17211** [comment]
![z5482860479380_4653124771cf237d7a865f1dc65343d1](https://github.com/Babyhamsta/Aimmy/assets/170990752/994af538-cbb5-4300-867b-cfffa034f484)
How to fix error code Runtime Exception?? Pls reply fast.
