### ISSUE TITLE
Error starting the model: [Erorrcode run time exception]

### ISSUE THREAD

**Issue by wal-ly** [Babyhamsta/Aimmy#1410]
I'm on a CPU only and I get this error every time I click on a model, I have all the requirements installed already

![image](https://github.com/Babyhamsta/Aimmy/assets/100832774/ce32744f-de84-456f-83fa-94bb95fe0df6)

**Comment by TooManyFactoryResets** [comment]
What is with the D:\. Are you running this off of a USB drive?

**Comment by whoswhip** [comment]
> I'm on a CPU only and I get this error every time I click on a model, I have all the requirements installed already
> 
> ![image](https://private-user-images.githubusercontent.com/100832774/331527502-ce32744f-de84-456f-83fa-94bb95fe0df6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzMzMzMsIm5iZiI6MTcxNjM3MzAzMywicGF0aCI6Ii8xMDA4MzI3NzQvMzMxNTI3NTAyLWNlMzI3NDRmLWRlODQtNDU2Zi04M2ZhLTk0YmI5NWZlMGRmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxMDE3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjVkODNmMzQwYzA5OGMyMTM4ZjQ1Y2NiMTY3NmNkNTJiYWM0MGE5MmQxMTAyZmFmZDAzMWQ1OWQ1YWI3ZTY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hFn5DrhA03_EznjiCxPc6-GvHHyUdeGM1GG6TaSuTgE)

yeah.... it doesnt work with cpu as of now, you will need a dedicated gpu.

**Comment by TaylorIsBlue** [comment]
Please understand that Aimmy usually doesn't work  well on computers without the following specs
CPU: minimum 4 cores (ex. i3 12100F)
RAM: 8 GB
GPU: NVIDIA Geforce GTX 1050 or equivalent
