### ISSUE TITLE
Aimmy does not open

### ISSUE THREAD

**Issue by MelvinSGjr** [Babyhamsta/Aimmy#1411]
I opened Aimmy but nothing happened

TotallyNotAimmyV2.exe is works (can crash if I load a large file model)

**Comment by TooManyFactoryResets** [comment]
Downloading 7.0 .NET desktop runtime worked for me. Make sure you click x64 to download not x86 [https://dotnet.microsoft.com/en-us/download/dotnet/7.0/runtime?cid=getdotnetcore&os=windows&arch=x64](https://dotnet.microsoft.com/en-us/download/dotnet/7.0/runtime?cid=getdotnetcore&os=windows&arch=x64)

**Comment by TooManyFactoryResets** [comment]
I only knew this because I ran AimmyLauncher.exe through Powershell instead of double clicking it.
