### ISSUE TITLE
7.0 .NET is being replaced with 8.0

### ISSUE THREAD

**Issue by TooManyFactoryResets** [Babyhamsta/Aimmy#1416]
I don't have much experience with VS but I wanted to point out that 7.0 .NET has reached EOL and is probably going to be replaced with [8.0](https://dotnet.microsoft.com/en-us/download/dotnet/8.0/runtime) or [9.0](https://dotnet.microsoft.com/en-us/download/dotnet/9.0/runtime)
![image](https://github.com/Babyhamsta/Aimmy/assets/155082829/ff9f066b-90ff-420d-85ea-fc54688f00d4)

**Comment by TaylorIsBlue** [comment]
V2 uses 8.0
