### ISSUE TITLE
Import custom model

### ISSUE THREAD

**Issue by hawx929** [Babyhamsta/Aimmy#1418]
I create onnx datapack, based on yolo8, but Aimmy errored, it still requires models based on. error 1x5x8400

**Comment by TooManyFactoryResets** [comment]
I'm pretty sure it needs to be v5 and not v8...

**Comment by TooManyFactoryResets** [comment]
Did you use the [Universalv3_web_model](https://github.com/Babyhamsta/Aimmy/tree/master/Universalv3_web_model) when using the editor?

**Comment by Babyhamsta** [comment]
1,6,8400 is not the correct output. We are looking for 5 outputs not 6.
Outputs being X, Y, Height, Width, and Confidence.
