### ISSUE TITLE
Software seems like a hoax .

### ISSUE THREAD

**Issue by versaud5** [Babyhamsta/Aimmy#1424]
This software claims you can use makesense.ai that uses yolov5 to train your images. But the  Aimmy can only load yolov8 models. There is no way makesense can make models for Aimmy. Hoax software.

**Comment by whoswhip** [comment]
Well you use makesense to LABEL your images then you train the model using yolov8, then convert it to an onnx file, there is no hoax in sight?

**Comment by Babyhamsta** [comment]
Dumb claims, you can always use other labeling software..
