### ISSUE TITLE
Does someone know any soulutions to this

### ISSUE THREAD

**Issue by RucOnYT** [Babyhamsta/Aimmy#1433]
![image_2024-06-24_151322333](https://github.com/Babyhamsta/Aimmy/assets/141345209/167da5cb-e5f1-4bbd-8e0e-c973f74f750d)

ive tried everything got .net framework 7.0 and 8.0 both and ive also made sure that it uses my gpu instead of cpu nothing seems to work its not even located on my d drive as i dont even have one and apparently my specs are also good enough so im out of ideas

My pc specs :
ram 8gb
cpu i5-4670k 4cores
gpu gtx 1050ti

**Comment by Lord-Nathan** [comment]
i get the same thing too ):

**Comment by Babyhamsta** [comment]
A few things,

#1. Ensure the .ZIP is fully extracted
#2. Ensure that you have all the dlls (OnnxRuntime/DirectML)

You said .net framework but you need .net runtime and redistributables. 
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.2-windows-x64-installer
https://aka.ms/vs/17/release/vc_redist.x64.exe
