### ISSUE TITLE
 trojan as part of a file for Aimmy

### ISSUE THREAD

**Issue by operator436** [Babyhamsta/Aimmy#1435]
Just found this trojan as part of a file for Aimmy an AI cheat for Hell Let Loose on github.
[AimmyV2.1.5.zip](http://aimmyv2.1.5.zip/) This is a Backdoor.MSIL.gkhl a malicious tool to give backdoor to your computer. They can then control your computer remotely however they want.
Cheats aren't free, they are trojans to attack our government, infrastructure, military targets, hold ransom attacks on our fortune 500 companies and much worse than you can imagine. Once these are installed they use your powerful gaming system to attack, blackmail and destroy assets. Maybe even use your computer to host child images. And you might get held responsible!
By installing these cheats for games, you are helping enemies of the free world be attacked. GetGud ... stop cheating!
PS
The author will lie their *ss off to tell you it's a false positive. Don't all criminals lie before the boof you in the *ss?
to see this for yourself go to [virustotal.com](http://virustotal.com/) drop the zip file on the website to have every single anti-virus in the known universe against it.

**Comment by Babyhamsta** [comment]
If you believe someone is uploading malware to Github you should report the upload. Github does do malware testing upon reports and you can provide your own scan results as well. I will also report this, thank you.

**Comment by Lather0519** [comment]
> 剛剛在 github 上發現這個木馬作為 Aimmy 檔的一部分，Aimmy 是 Hell Let Loose 的 AI 作弊器。 [AimmyV2.1.5.zip](http://aimmyv2.1.5.zip/) 這是一個Backdoor.MSIL.gkhl惡意軟體，用於為您的電腦提供後門。然後，他們可以隨心所欲地遠端控制您的電腦。作弊不是免費的，它們是特洛伊木馬，可以攻擊我們的政府、基礎設施、軍事目標，對我們的財富 500 強公司進行贖金攻擊，而且比您想像的要糟糕得多。一旦安裝了這些，他們就會使用您強大的遊戲系統來攻擊、勒索和破壞資產。甚至可以使用您的電腦來託管子圖像。你可能會被追究責任！通過為遊戲安裝這些作弊器，您正在説明自由世界的敵人受到攻擊。GetGud ...別作弊了！ PS 作者會撒謊告訴你這是一個誤報。不是所有的罪犯都在 *ss 中躺在你面前嗎？要親自查看此內容 [virustotal.com](http://virustotal.com/) 請轉到網站上的 zip 檔，以使已知宇宙中的每一個防病毒軟體都針對它。

Aimmy is a great free product

I understand your concern but someone using aimmy for online multiplayer cheating is something that the team can't control and for that reason they haven't enhanced or added aimmy's anti-detection performance on games that have already been detected so stop crying and report cheaters you think are ok and the game company will deal with it.

**Comment by node4js** [comment]
Slide the report, aimmy cuda has 734mb in size, it's not even physically possible to upload that to vt?

**Comment by pr0grammed** [comment]
> Slide the report, aimmy cuda has 734mb in size, it's not even physically possible to upload that to vt?

I was wondering the same thing but can't you just remove the unnecessary files that you can confirm are safe then zip it and scan it that way?

**Comment by node4js** [comment]
> > Slide the report, aimmy cuda has 734mb in size, it's not even physically possible to upload that to vt?
> 
> I was wondering the same thing but can't you just remove the unnecessary files that you can confirm are safe then zip it and scan it that way?

onnxruntime, cuda files, libraries

**Comment by b2311319filip-ops** [comment]
safe

**Comment by ilovemulberrycounty4** [comment]
virus total can scan the entire thing btw and it detected numerous trojans from what i saw, i am not a programmer or a professional i am saying what virustotal is putting on the table, 


edit: i used malwarebytes and virus total inside of a virtual machine. it is a malware confirmed. do not download

**Comment by node4js** [comment]
> virus total can scan the entire thing btw and it detected numerous trojans from what i saw, i am not a programmer or a professional i am saying what virustotal is putting on the table,
> 
> edit: i used malwarebytes and virus total inside of a virtual machine. it is a malware confirmed. do not download

More than obviously gonna get flagged, it's literally manipulating mouse input
