### ISSUE TITLE
ONNX runtime "The parameter is incorrect"

### ISSUE THREAD

**Issue by callmejaf** [Babyhamsta/Aimmy#1445]
I have been sat here for the past 3 hours trying to build this project. What am I doing wrong? This happens whenever I try to select any of the onnx models. However, it works fine downloading the release verison. 

2024-07-18 19:26:58.1287606 [E:onnxruntime:, inference_session.cc:2045 onnxruntime::InferenceSession::Initialize::<lambda_deb1d9a98dc3fb814563870e4f4b9f20>::operator ()] Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\AbiCustomRegistry.cpp(519)\onnxruntime.DLL!00007FFB2FFE1B66: (caller: 00007FFB30015757) Exception(3) tid(45b0) 80070057 The parameter is incorrect.

2024-07-18 19:26:59.4645567 [E:onnxruntime:, inference_session.cc:2045 onnxruntime::InferenceSession::Initialize::<lambda_deb1d9a98dc3fb814563870e4f4b9f20>::operator ()] Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\AbiCustomRegistry.cpp(519)\onnxruntime.DLL!00007FFB2FFE1B66: (caller: 00007FFB30015757) Exception(6) tid(45b0) 80070057 The parameter is incorrect.

**Comment by yungDoom** [comment]
do you have onnxruntime.dll inside your bin\Release or bin\Debug folder?

**Comment by yungDoom** [comment]
It should look like this after compiling latest version of Aimmy-V2:
![image](https://github.com/user-attachments/assets/296031e4-43ff-4a59-9697-551672416a29)

Do this steps:
First of all, Copy **System.Management.dll** from runtimes\win\lib\*netversion*\ to aimmy root
and then Copy **onnxruntime.dll** from runtimes\*architecture*\native\ to aimmy root

Also you need this dll from aimmy's [latest release](https://github.com/Babyhamsta/Aimmy/releases/tag/v2.1.5):
**DirectML.dll**

**Comment by yungDoom** [comment]
It should look like this to make it work:
![Screenshot 2024-07-19 124333](https://github.com/user-attachments/assets/534f9645-168f-4f0c-8444-f4cc40a2958b)

You need **onnxruntime.dll** and **DirectML.dll**

onnxruntime.dll = You can find it inside runtimes\win-x64\native folder, put it to the TotallyNotAimmyV2.exe root.
DirectML.dll = You can get it from the [Latest Version of Aimmy in Releases](https://github.com/Babyhamsta/Aimmy/releases/tag/v2.1.5)

**Comment by yungDoom** [comment]
It should look like this to make it work:
![Screenshot 2024-07-19 124333](https://github.com/user-attachments/assets/534f9645-168f-4f0c-8444-f4cc40a2958b)

You need **onnxruntime.dll**, **DirectML.dll** and **System.Management.dll**

onnxruntime.dll = You can find it inside runtimes\win-x64\native\ folder, put it to the TotallyNotAimmyV2.exe root.
DirectML.dll = You can get it from the [Latest Version of Aimmy in Releases](https://github.com/Babyhamsta/Aimmy/releases/tag/v2.1.5)
System.Management.dll = Can be obtained in runtimes\win\lib\*netversion*\

**Comment by TaylorIsBlue** [comment]
Make sure that when you are debugging, you change from Any CPU to X64, theres a dropdown next to the green play button to debug your build of aimmy that usually says Any CPU.

**Comment by yungDoom** [comment]
Yeah that will get all the files automatically and make it work without any modifications, you should switch to x64 as taylorisblue said.

**Comment by elderCZE** [comment]
Try this version https://www.mediafire.com/file/0pa4ngew4gz99cw/aimmy_Updated.rar/file
