### ISSUE TITLE
Warface | Не работает AIM assits

### ISSUE THREAD

**Issue by antinachai9** [Babyhamsta/Aimmy#1446]
На уровне ядра не пробовал, а вот все остальные методы не работают

**Comment by elderCZE** [comment]
Попробуйте это, это программа обновления https://www.mediafire.com/file/pdvlcgmh3dnxlxf/Aimmy_Updater.rar/file

**Comment by elderCZE** [comment]
This version works for me https://www.mediafire.com/file/0pa4ngew4gz99cw/aimmy_Updated.rar/file
