### ISSUE TITLE
[Support] random models for single games

### ISSUE THREAD

**Issue by a-sajjad72** [Babyhamsta/Aimmy#1450]
Really appreciate your work... But I have some queries regarding models. I had seen multiple models for single game at `Aimmy/models`. What are the differences between them? example for Apex Legends shown below.

||
|---|
|Apex Legends (20k) by brock.onnx|
|Apex Legends (20k).onnx|
|Apex Legends [V2] by klueishim.onnx|
|Apex Legends [V3] by Dudes Banned.onnx|
|Apex Legends by 5pr.onnx|
|Apex Legends by Blue.onnx|
|Apex Legends by josh-atx04.onnx|
|Arsenal (4K) by Themida.onnx|

**Comment by yungDoom** [comment]
They are made by different peoples.

**Comment by ByfronTechnologies** [comment]
Are you using this on Roblox?

**Comment by a-sajjad72** [comment]
> Are you using this on Roblox?

nope.

**Comment by Lofuuzi** [comment]
![12](https://github.com/user-attachments/assets/16028a42-f1ed-440d-a6d6-dbd29d88b3b3)

**Comment by Babyhamsta** [comment]
Pretty much, what the first guy said. They are made by different people. I would like to standardize them in the future so they would include a last updated date, and the amount of images trained on.
