### ISSUE TITLE
Is there a way to not get autobanned?

### ISSUE THREAD

**Issue by joemamabeats** [Babyhamsta/Aimmy#1451]
Lets say i want to use aimmy only on Cod where it isnt detected, if i launch apex legends i will get auto banned even if i dont even open it. Is there a way to avoid this?

**Comment by ByfronTechnologies** [comment]
Oh, thank god you're not using it on Roblox.. 
I'll be VERY angry at you if you do!!!

**Comment by yungDoom** [comment]
> Oh, thank god you're not using it on Roblox.. I'll be VERY angry at you if you do!!!

I'm using this cheat in roblox, what you can do to me?

**Comment by ByfronTechnologies** [comment]
whoever said, "I'm using this cheat in Roblox, what can you do to me?" I'm crying!!! you make me so sad

**Comment by yungDoom** [comment]
> whoever said, "I'm using this cheat in Roblox, what can you do to me?" I'm crying!!! you made me so sad

I said that, i deleted my comment because i didn't wanted to make you more sad..

**Comment by ByfronTechnologies** [comment]
> > Whoever said, "I'm using this cheat in Roblox, what can you do to me?" I'm crying!!! you made me so sad
> 
> I said that I deleted my comment because I didn't want to make you more sad..

thank you so much I'm happy now

**Comment by ByfronTechnologies** [comment]
> > whoever said, "I'm using this cheat in Roblox, what can you do to me?" I'm crying!!! you made me so sad
> 
> can u pls remove urself from roblox thanks!

No.

**Comment by imqxod** [comment]
> > > whoever said, "I'm using this cheat in Roblox, what can you do to me?" I'm crying!!! you made me so sad
> > 
> > 
> > can u pls remove urself from roblox thanks!
> 
> No.

can u unban my acc then :3

**Comment by imqxod** [comment]
> > > whoever said, "I'm using this cheat in Roblox, what can you do to me?" I'm crying!!! you made me so sad
> > 
> > 
> > can u pls remove urself from roblox thanks!
> 
> No.

Btw, I've made a honeypot executor sir.

**Comment by Lofuuzi** [comment]
![12](https://github.com/user-attachments/assets/b7697de3-18de-4c0e-ab5e-62bacb3c2a12)

**Comment by ByfronTechnologies** [comment]
> > > > whoever said, "I'm using this cheat in Roblox, what can you do to me?" I'm crying!!! you made me so sad
> > > 
> > > 
> > > can u pls remove urself from roblox thanks!
> > 
> > 
> > No.
> 
> Btw, I've made a honeypot executor sir.

I love you

**Comment by ByfronTechnologies** [comment]
> > > > whoever said, "I'm using this cheat in Roblox, what can you do to me?" I'm crying!!! you made me so sad
> > > 
> > > 
> > > can u pls remove urself from roblox thanks!
> > 
> > 
> > No.
> 
> Btw, I've made a honeypot executor sir.

I love you

**Comment by imqxod** [comment]
> > > > > whoever said, "I'm using this cheat in Roblox, what can you do to me?" I'm crying!!! you made me so sad
> > > > 
> > > > 
> > > > can u pls remove urself from roblox thanks!
> > > 
> > > 
> > > No.
> > 
> > 
> > Btw, I've made a honeypot executor sir.
> 
> I love you

I love you too
