### ISSUE TITLE
why did i get banned

### ISSUE THREAD

**Issue by kittyslayer** [Babyhamsta/Aimmy#1456]
i was in genral when i was looking thru my gifs and miss clicked and then some people sed hi i sed hi and then i got banned i even sed in the discord chat "opps didnt mean to send that" and i was still banned is there anyway to get unbanned DISCORD-zombiefl2857

**Comment by Lofuuzi** [comment]
![12](https://github.com/user-attachments/assets/bfc7db5b-7a2c-4bfc-b35e-ac8a0ca8fe38)

**Comment by Lofuuzi** [comment]
no, they are weirdo, accepted it
