### ISSUE TITLE
how to delete aimmy fully???????? i stilll get kicked in game when i already deleted files

### ISSUE THREAD

**Issue by vxqz5** [Babyhamsta/Aimmy#1465]

**Comment by MarsInsanity** [comment]
You just delete the folder, however you can check appdata/local for any trace folders left.

**Comment by vxqz5** [comment]
nothing with it but i get kicked from the game. ive uninstalled the game and reinstalled it same issue. my alt got banned after i tried to ready up again after the ban

**Comment by vxqz5** [comment]
![Screenshot 2024-09-15 124110](https://github.com/user-attachments/assets/3963ea81-0718-4664-bfe7-828fba30d4af)

**Comment by Babyhamsta** [comment]
If you used one of the driver methods, you'll need to reboot as the driver could be loaded still. Other that that there should be nothing that persists, Fortnite does drop traces and HWID bans so there is a potential you'll have to reinstall windows and spoof to get around a ban. We are not responsible for bans.
