### ISSUE TITLE
Labeling using my own model

### ISSUE THREAD

**Issue by mortezaghafoori** [Babyhamsta/Aimmy#1484]
Is there anyway to convert my trained model into a format where I can use it it makesense . ai so the automatic detection gets better every time I train my model on more pictures? I don't know if this is possible or not but it would be very awesome to be able to do that. Thanks!

**Comment by mortezaghafoori** [comment]
Any idea guys?

**Comment by Babyhamsta** [comment]
Makesense.ai is a bit outdated and only takes in YOLOv5 models, there are other tools that can be used with YOLOv8 models just fine such as AnyLabeling which will run models locally against your images.

https://github.com/CVHub520/X-AnyLabeling
