### ISSUE TITLE
[MISC] I have created a training notebook on google colab

### ISSUE THREAD

**Issue by RealCalumPlays** [Babyhamsta/Aimmy#26]
Basically I have created a full guide and training notebook on google colab. I have already sent the details to Babyhamsta but I wanted you guys opinions on whether you guys are okay with me releasing it. All the code is source-available and suitable credits have been added to the notebook. I will not send the link here unless you two want me to.

- Saul

**Comment by RealCalumPlays** [comment]
Also on an unrelated note my mouse sensitivity is wayy too fast even on the lowest setting. It moves it sometimes completely to the top and corner of the window.

**Comment by kingsommar** [comment]
shore

**Comment by l3afai** [comment]
send it pls
