### ISSUE TITLE
[Question] I think i did it ? 

### ISSUE THREAD

**Issue by Catplayz2011** [Babyhamsta/Aimmy#37]
![cmd_vAdlbr0v2G](https://github.com/Babyhamsta/Aimmy/assets/144529766/fa7e1b67-6489-4b80-979e-301c92103010)

Well I uninstalled python and installed the UWP python 3.10 version and it just gave me a warning is it normal that warning ? It didnt gave me any error. Is it unltralytics in stalled now ?

![image](https://github.com/Babyhamsta/Aimmy/assets/144529766/7de2dd58-c51f-4d7e-8b74-3f2c44932743)

**WARNING MESSAGE :**:

  WARNING: The script cpuinfo.exe is installed in 'C:\Users\Miizu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script isympy.exe is installed in 'C:\Users\Miizu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script f2py.exe is installed in 'C:\Users\Miizu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'C:\Users\Miizu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script normalizer.exe is installed in 'C:\Users\Miizu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tqdm.exe is installed in 'C:\Users\Miizu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts convert-caffe2-to-onnx.exe, convert-onnx-to-caffe2.exe and torchrun.exe are installed in 'C:\Users\Miizu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

![image](https://github.com/Babyhamsta/Aimmy/assets/144529766/440a768c-04d2-4295-b1e6-3a38ee3be211)

_Is it installed now or not ?_

**Comment by Catplayz2011** [comment]
> ![cmd_vAdlbr0v2G](https://user-images.githubusercontent.com/144529766/279184690-fa7e1b67-6489-4b80-979e-301c92103010.png)
> 
> Well I uninstalled python and installed the UWP python 3.10 version and it just gave me a warning is it normal that warning ? It didnt gave me any error. Is it unltralytics in stalled now ?
> 
> ![image](https://user-images.githubusercontent.com/144529766/279185549-7de2dd58-c51f-4d7e-8b74-3f2c44932743.png)
> 
> **WARNING MESSAGE :**:
> 
> WARNING: The script cpuinfo.exe is installed in 'C:\Users\Miizu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH. Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location. WARNING: The script isympy.exe is installed in 'C:\Users\Miizu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH. Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location. WARNING: The script f2py.exe is installed in 'C:\Users\Miizu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH. Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location. WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'C:\Users\Miizu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH. Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location. WARNING: The script normalizer.exe is installed in 'C:\Users\Miizu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH. Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location. WARNING: The script tqdm.exe is installed in 'C:\Users\Miizu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH. Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location. WARNING: The scripts convert-caffe2-to-onnx.exe, convert-onnx-to-caffe2.exe and torchrun.exe are installed in 'C:\Users\Miizu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH. Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> 
> ![image](https://user-images.githubusercontent.com/144529766/279185837-440a768c-04d2-4295-b1e6-3a38ee3be211.png)
> 
> _Is it installed now or not ?_

C:\Users\Miizu\Documents\ShareX\Screenshots\2023-10\cmd_2mG77iX2Po.png

But I still cant train it... So i gues its not installed.

**Comment by Catplayz2011** [comment]
Its wont let me train it still : 

![image](https://github.com/Babyhamsta/Aimmy/assets/144529766/abfa15a2-0f00-45cf-ad98-176b99b56a65)

So I guess its not installed.

**Comment by Babyhamsta** [comment]
Like I said in the previous ticket we don't offer support for 3rd party items. You'll need to open a ticket on their Github.

Thanks
-Hamsta
