### ISSUE TITLE
[Question] Where can I copy StartTrain.txt and Export.txt ? (From the video)

### ISSUE THREAD

**Issue by Catplayz2011** [Babyhamsta/Aimmy#38]
the commad I tried to write isnt working, so i would like to know  where i can copy these cmds.

**Comment by natdog400** [comment]
[Export.txt](https://github.com/Babyhamsta/Aimmy/files/13210824/Export.txt)
[start training.txt](https://github.com/Babyhamsta/Aimmy/files/13210825/start.training.txt)
here you go change to what you want of course but those are the commands the .pt is needs to be the best.pt from the training
