### ISSUE TITLE
Error when choosing a Model (I downloaded 2015-2022 VC Redist x64)

### ISSUE THREAD

**Issue by LegoScripter** [Babyhamsta/Aimmy#39]
Even after I downloaded it, it still happening and the last issue about that was closed as solved so I was wondering if I gotta do something else

**Comment by Zolura** [comment]
same issue, also downloaded all the required files

**Comment by Babyhamsta** [comment]
Please try installing this and let me know if that resolves the issue: https://www.microsoft.com/en-us/download/confirmation.aspx?id=35

Thanks!

**Comment by LegoScripter** [comment]
Still not working

**Comment by Babyhamsta** [comment]
Both issue https://github.com/Babyhamsta/Aimmy/issues/18 and https://github.com/Babyhamsta/Aimmy/issues/32 had this issue and resolved it by downloading certain libs/redistributables. You may try each of the ones they included in their photos. If you happen to find which one fixes it I would greatly appreciate knowing. I will attempt to setup a VM box to do some testing with a fresh install of Windows.

**Comment by Zolura** [comment]
Still same error, already installed directx. Downloaded all those libs/redists [provided](https://user-images.githubusercontent.com/149288492/278898563-73c6612a-75a8-494f-9e29-29f71c78e37e.png) by [KingSommar](https://github.com/Babyhamsta/Aimmy/issues/32#issuecomment-1784223733)
Used these links:
https://github.com/abbodi1406/vcredist/releases/tag/v0.76.0 (vc redist all in one installation)
https://www.microsoft.com/en-us/download/details.aspx?id=20914 (xna framework)
https://www.openal.org/downloads/oalinst.zip (oalinst)
https://www.microsoft.com/en-us/download/confirmation.aspx?id=35 (directx runtime)
https://dotnet.microsoft.com/en-us/download/dotnet-framework (.net framework)

**Comment by LegoScripter** [comment]
Same thing, downloaded all that libs/redists and still error

**Comment by LegoScripter** [comment]
I bought a new PC and worked, so basically it doesn't work in some graphics cards
