### ISSUE TITLE
Aim Aligner doesn't work

### ISSUE THREAD

**Issue by okbobo** [Babyhamsta/Aimmy#42]
The Aim Aligner doesn't work for me, I tried it on popular FPS games (like phantom forces, arsenal)  with both models but it doesn't work. All it does is just shift my aim into the Air sometimes. The auto trigger also just shoots randomly sometimes. Can this get fixed?

**Comment by okbobo** [comment]
instead of doing nothing it just shifts to random places. example i try to point at player, aim aligner shifts to wall.

**Comment by Babyhamsta** [comment]
> instead of doing nothing it just shifts to random places. example i try to point at player, aim aligner shifts to wall.

It still sounds like your aim sensitivity is too high.. It's like you didn't even read my first response. Please provide an image of the UI so I can verify your settings.

**Comment by okbobo** [comment]
![image](https://github.com/Babyhamsta/Aimmy/assets/133570436/6c02f272-ddb7-43a8-9e9f-bf63710d79d5)
![image](https://github.com/Babyhamsta/Aimmy/assets/133570436/9eedf968-a220-49d3-9b12-b2f9d55a8a65)
![image](https://github.com/Babyhamsta/Aimmy/assets/133570436/d6ec912c-163d-4565-ba3e-df7fff3a0431)

**Comment by maik8326** [comment]
Btw your roblox cam movement can speed up mouse i set to my 0.2000 or say 0.2 in roblox

**Comment by Babyhamsta** [comment]
> Btw your roblox camera sensitivity movement can speed up mouse i set to my 0.2000 or say 0.2 in roblox

Yes, in game sensitivity can affect the aim as well. My current sensitivity for ROBLOX is 0.01 or 0.02 personally and I use about 0,75 as my mouse sensitivity. I have a high DPI mouse though.
