### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by PericoSpart** [Babyhamsta/Aimmy#47]
When I train my models it takes 12 minutes to train an epoch, it tells me I have 0G on GPU Memory even though the GTX 1060 has way more. This makes training extremely painfully slow. Did I install ultralytics wrongly? Because I followed the tutorial step by step.

**Comment by PericoSpart** [comment]
Asked ultralytics github instead of Aimmy.

**Comment by PericoSpart** [comment]
Issue open because of no answers.

**Comment by PericoSpart** [comment]
Fixed.

**Comment by PericoSpart** [comment]
Not fixed.

**Comment by Babyhamsta** [comment]
We do not offer support for training, you'll need to contact their support or look at their documentation on Ultralytics.
