### ISSUE TITLE
Program crashes after I select a model

### ISSUE THREAD

**Issue by bananaman08** [Babyhamsta/Aimmy#49]
![image_2023-11-01_220415409](https://github.com/Babyhamsta/Aimmy/assets/105743921/51b9f50e-198f-4943-aa5c-31e3c9ff3015)

**Comment by Babyhamsta** [comment]
Duplicate of https://github.com/Babyhamsta/Aimmy/issues/18, https://github.com/Babyhamsta/Aimmy/issues/32, https://github.com/Babyhamsta/Aimmy/issues/39, and https://github.com/Babyhamsta/Aimmy/issues/41

**Comment by scriptedradio** [comment]
Is there a fix for it?
