### ISSUE TITLE
question

### ISSUE THREAD

**Issue by poke000000000** [Babyhamsta/Aimmy#50]
can i use this on valorant to train it or will the anticheat ban me?

**Comment by NikoWiki** [comment]
i got a model for that game if you want to try not going to try it out myself tho cords hotthewog

**Comment by Babyhamsta** [comment]
Valorant has a KERNEL level anti-cheat if I do remember correctly, this will not bypass any of their false mouse detections.  With some modifications you could run this off a USB and have it control a mouse that is made to be cheated with aka one that allows you to fake driver inputs.

**Comment by HandSomeNissan** [comment]
What are the modifications? Is there any tutorials to do this?
