### ISSUE TITLE
[ Suggestion ] Please add configs 

### ISSUE THREAD

**Issue by nxtcapi** [Babyhamsta/Aimmy#51]
title says it all

**Comment by natdog400** [comment]
i tried to have one added but.... i got one i made for riotfall that i found works one riotfall recoil frontlines and ironsight on steam lol even tho i think i just got banned not sure can still play but got a weird message after closing iron so prob detected dont use on it but it did work so yes i agree but @nxtcapi it took me 5 hours to collect my images then 2 1/2 hours to label them then 9 hours to train so please be patient i take mad time to perfect an ai model mine will prob suck compared to the ones they release with this amount of time passing before an update

**Comment by MarsQQ** [comment]
Hey!

Do you mean the ability to hotswap settings (mouse sensitivity, ai confidence, etc)? Since that is something that I am planning to work on very soon :)

- Nori

**Comment by MarsQQ** [comment]
> [Riotfall.zip](https://github.com/Babyhamsta/Aimmy/files/13257449/Riotfall.zip) i tried to have one added but.... i got one i made for riotfall that i found works one riotfall recoil frontlines and ironsight on steam lol even tho i think i just got banned not sure can still play but got a weird message after closing iron so prob detected dont use on it but it did work so yes i agree but @nxtcapi it took me 5 hours to collect my images then 2 1/2 hours to label them then 9 hours to train so please be patient i take mad time to perfect an ai model mine will prob suck compared to the ones they release with this amount of time passing before an update

Thank you for making a model :))),
If you don't mind, can we add this into Aimmy as a preloaded model? I'll be testing this personally, and I will be asking about it to BabyHamsta too.

We haven't released an update in a while because we all have a lot of stuff to do outside of Aimmy. But don't worry, we're still in active development and have some things planned in the background :D

Thanks!
- Nori

**Comment by natdog400** [comment]
you can absolutly add it!!!! yay thank you

**Comment by Visionishere** [comment]
this issue should be pinned so everyone can add configs here. also, im working on a bad business config. i have 2k images currently. The video tutorial is a bit long and confusing so I might not be able to finish it but we shall see.

**Comment by MarsQQ** [comment]
Hotswap Configurator Added - 26/11/23
