### ISSUE TITLE
Basic FN model!

### ISSUE THREAD

**Issue by vanishLLC** [Babyhamsta/Aimmy#55]
Hello there In this issue I'm sending images and some trained data for FN suddenly I have a problem with making my model so I'm just linking images and data here!
[labels_my-project-name_2023-11-07-07-57-57.zip](https://github.com/Babyhamsta/Aimmy/files/13312489/labels_my-project-name_2023-11-07-07-57-57.zip)
And Images!
https://www.mediafire.com/file/zejrnli44hgkkrh/images.zip/file (Images were 583MB but you can import 25MB max

**Comment by Babyhamsta** [comment]
What is FN? If it is short for something can you provide the full description and possibly a link to the game?

**Comment by MarsQQ** [comment]
> What is FN? If it is short for something can you provide the full description and possibly a link to the game?

I'm 80% sure he means fortnite

- Nori

**Comment by vanishLLC** [comment]
@Babyhamsta fn stands for fortnite

**Comment by natdog400** [comment]
@vanishLLC going to have to relabel but ill see what i can do for you!!!!

**Comment by vanishLLC** [comment]
@natdog400 specially for you i made larger pack! 
[labels_my-project-name_2023-11-10-11-43-34.zip](https://github.com/Babyhamsta/Aimmy/files/13323589/labels_my-project-name_2023-11-10-11-43-34.zip)
And Images
https://mega.nz/file/2MJlwArR#J4Z7e5O-xa-vqbDksuGZcShM8w9Fs0zEu1AoJTP32U0

**Comment by natdog400** [comment]
imma download fn and play in some arenas get even more pic for you ok im working on it i promise!!

**Comment by natdog400** [comment]
so in another post i have called upgradedAIO this is previews of it in action!

https://github.com/Babyhamsta/Aimmy/assets/24785253/c769f076-fecf-4ad5-b939-f01ffc269b7c


https://github.com/Babyhamsta/Aimmy/assets/24785253/3dce7815-c58b-4689-b03e-3a4a10a8fe3b

![uB9Uxu3OXN](https://github.com/Babyhamsta/Aimmy/assets/24785253/2bb3c4cb-7787-4866-8f77-905820f04f28)

**Comment by Notbruh1** [comment]
lol bro its detected

**Comment by natdog400** [comment]
idc about the game so if my acc get banned for making a model for someone else who wants to get banned so be it but for hrs it hasnt been for me been playing in free for all

**Comment by Notbruh1** [comment]
nah just talking about the driver that aimmy uses is detected on fortnite

**Comment by Notbruh1** [comment]
> so in another post i have called upgradedAIO this is previews of it in action!
> 
>  CZzfuLSYEY.mp4 
>  O4U6R6UtgR.mp4

what is upgradedAIO

**Comment by natdog400** [comment]
just the name of the model in another issues section i should have posted those there now i think about it

**Comment by Notbruh1** [comment]
what sens do you use

**Comment by Notbruh1** [comment]
on program

**Comment by Notbruh1** [comment]
some guy "apparently" selling aimmy with "undetected" drivers for fortnite
![image](https://github.com/Babyhamsta/Aimmy/assets/80576979/3625d12f-e79a-4fef-a507-55245250ed7c)

**Comment by Babyhamsta** [comment]
> some guy "apparently" selling aimmy with "undetected" drivers for fortnite ![image](https://user-images.githubusercontent.com/80576979/282266588-3625d12f-e79a-4fef-a507-55245250ed7c.png)

I wouldn't trust that, first off it's hard to secure the fake mouse movements but there are ways to make it more obscure. Aimmy is not paid nor would I trust anyone selling it with a driver.

**Comment by Notbruh1** [comment]
ofc i wouldn't use some random "fix" that is also paid

**Comment by Babyhamsta** [comment]
Merged
