### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Niggywiggy** [Babyhamsta/Aimmy#56]
Maybe make a discord where people can share models.

**Comment by TONNNoor** [comment]
Same idea but waiting for the confirmation

**Comment by Babyhamsta** [comment]
We plan on allowing people to upload models here on github and download them into the UI.

**Comment by TONNNoor** [comment]
> We plan on allowing people to upload models here on github and download them into the UI.

I tried making a model but, it seems that it doesn't work, idk if it's a problem with the setting or something else, but maybe you could give us some bit of basic info like, atleast how many images are required to be used to make models and is it possible to combine images from random games into a one model, and the 640 frame is a required thing or i can use a bigger picture?

**Comment by vxzl** [comment]
> Maybe make a discord where people can share models.

A general discord for Aimmy has presets, models etc.
https://discord.gg/aimmy
