### ISSUE TITLE
After like 5-10 minutes freezes pc and crashes it entirely, but everytime it freezes, I have to relaunch it to make it work again (Just read what I typed in issue request cuz yes, pls)

### ISSUE THREAD

**Issue by SadlekAski** [Babyhamsta/Aimmy#57]
Sometimes it just freezes for 30 seconds and crashes roblox and discord. sometimes it just freezes
BUT everytime it freezes it stops working and I have to relaunch it

My graphic card is from AMD
rx 460  (As I remember, I'm not sure)
pls fix if possible

I'll say what I did:
I choosed one of two models that are built-in program (It crashes my pc on both)
Enabled fov and aim align (Or whatever the aim thing named)
Playing normally using aimbot
Then at one moment my pc freezes entirely (Cant even alt+tab or do anything, just stays same image)
After like 30 seconds - 3 minutes it unfreezes and there can happen one of three things
1. Unfreezes, My pc will crash entirely (my pc will restart itself), Aimmy stops working (I have to relaunch it), Programs that was launched are stay launched but same as 2nd situation Roblox and Discord crashing
2. Unfreezes, Roblox And Discord will crash (Other things such as steam and aimmy itself will stay open), Aimmy stops working (I have to relaunch it)
3. Unfreezes, nothing will crash, Aimmy stops working and I have to relaunch it

**Comment by MarsQQ** [comment]
Hmm, I'm not sure what to do here, @Babyhamsta might know what is up.

- Nori

**Comment by quanmanss11** [comment]
https://github.com/microsoft/onnxruntime/issues/12761 ,,,,,,,,,,, to make sure im not stupid this link also have rx 480 and crash

**Comment by Babyhamsta** [comment]
I am not sure on the freezing part, we haven't had any other reports on that. I do know that AMD cards struggle with running models as AMD doesn't have any acceleration for Windows like Nivida. Their RocM should be coming to Windows soon and with that they should get the same performance as Nivida cards when it comes to running models but currently there isn't a whole lot we can do.
