### ISSUE TITLE
Arsenal Model

### ISSUE THREAD

**Issue by whoswhip** [Babyhamsta/Aimmy#61]
Hey so I was making a model for [Arsenal](https://www.roblox.com/games/286090429/Arsenal) but I ran into an issue which I'm still trying to fix where it cant find the labels but if someone either would like to help me or finish the model I'd be very grateful.

[Lables](https://drive.google.com/drive/folders/1OZnEOS81vUcLUIATZpb7XAapvMY-pPHF?usp=sharing)

[Images](https://drive.google.com/drive/folders/1QRc2kSUzvH4PTBDq2oSVX3O6PhAu6XN0?usp=sharing)

**Comment by TONNNoor** [comment]
You gotta wait it needs hours
