### ISSUE TITLE
Add Lost Light and Escape from Tarkov Model

### ISSUE THREAD

**Issue by memes231** [Babyhamsta/Aimmy#62]
i want to add lost light because it's my favorite game and eft is my fav game so do you want to add it?

**Comment by MarsQQ** [comment]
I don't have the game, but you're free to make a model of it if you like.

**Comment by natdog400** [comment]
the one of mine that got added works for lost light just tested

**Comment by Babyhamsta** [comment]
> i want to add lost light because it's my favorite game and eft is my fav game so do you want to add it?

We don't take model requests, we have a few pre-provided models for ROBLOX but other than that users can create their own, we have some tutorials on how to make a YOLOv8 model and convert it to Onnx format. https://github.com/Babyhamsta/Aimmy#how-do-i-train-my-own-model
