### ISSUE TITLE
Training question

### ISSUE THREAD

**Issue by Cattodog** [Babyhamsta/Aimmy#63]
Can you, on makesense.ai, put the head as the only target for the ai to shoot at or will it not shoot right and, or shoot teamates?

**Comment by natdog400** [comment]
you could but im pretty sure its less reliable look at it this way think of it the same as your eyes easier to see a whole body or just a head, if i was you use the whole body then change the y value of the aligner to aim at head

**Comment by Babyhamsta** [comment]
We don't have any control on MakeSense, that isn't part of this project, just a tool we prefer for labeling images. Our models are offered for free, you can use the left/right offset to help adjust off aim.
