### ISSUE TITLE
would anyone want a ai auto labeler in python for pretty much any game?

### ISSUE THREAD

**Issue by NikoWiki** [Babyhamsta/Aimmy#67]
Lemme know if this will to any use for anybody it works via Youtube videos and the frames in them you can change that for something else if you want as well.

**Comment by NikoWiki** [comment]
https://discord.gg/v7p2krmd posted it in here

**Comment by Babyhamsta** [comment]
The only "auto label" that would be semi useful would be AutoDistill. It wouldn't work for this case most likely and it still relies on pre-trained large models. You could use a different AI other than object detection but that would take a lot of work to put together and maintain.
