### ISSUE TITLE
Aim aligner not responsive

### ISSUE THREAD

**Issue by ontop69** [Babyhamsta/Aimmy#70]
I'm using 0.04 sens on roblox, 800 dpi and 0.75 mouse sens with 0.45 confidence yet when I aim it doesn't seem to move my crosshair at all unless I see their entire body and it moves somewhat slow and at some points it would suddenly shift almost as if theirs some kind of delay when aiming at them.

**Comment by TONNNoor** [comment]
try increasing it to 0.98 on aimmy or something between 95 and 99

**Comment by Babyhamsta** [comment]
The higher the mouse sens the slower the mouse movements are. You should try a sens around 50-60 for a very snappy aimbot.
