### ISSUE TITLE
If I try to Load Model, Aimmy crashes fully.

### ISSUE THREAD

**Issue by Az4re** [Babyhamsta/Aimmy#73]
Well, like said in Title, whenever I press on any Model to load, it crashes.
maybe also important is, that when roblox is open/I open it while Aimmy is crashed it crashes aswell.

**Comment by Babyhamsta** [comment]
Was there any error message provided with the crash?

**Comment by ahhtuansz** [comment]
yes it said this 
![Aimmy 11_23_2023 9_28_39 PM](https://github.com/Babyhamsta/Aimmy/assets/123877525/1f3906de-2932-432d-b9bd-658d96eb0efb)

**Comment by ahhtuansz** [comment]
> Was there any error message provided with the crash?

yes

**Comment by Az4re** [comment]
> Was there any error message provided with the crash?

No, it just closed and gone.
but It's fixed for me now.
