### ISSUE TITLE
Aim assist just flings my mouse

### ISSUE THREAD

**Issue by yyaridev** [Babyhamsta/Aimmy#75]
When i press the trigger key and an enemy is in my fov my pointer just "gets thrown" away from the enemy.
I have no idea on how to describe it so heres a video too:
[https://streamable.com/pr0t9d](https://streamable.com/pr0t9d)

**Comment by Babyhamsta** [comment]
Mouse sensitivity is too high, please try a higher number such as 70-90, it sort of depends on your in-game sensitivity too.
