### ISSUE TITLE
Mouse drive implementation, Ghub or Interception

### ISSUE THREAD

**Issue by Gemini899** [Babyhamsta/Aimmy#76]
since many games detect Winapi mouse movement is possible to use ghub drivers?, there are alreay other aimbot that use it should be pretty easy to implement and it wil take this aimbot to the next level since in may games like"bf2042" the winapy gets detected by EA anti cheat and the mouse stop moving after 3-4 seconds of working

**Comment by Babyhamsta** [comment]
You are more than welcome to fork Aimmy and add your own implementation of ghub driver support. Not everyone has a Logitech. We do plan on looking into other options than WinAPI as there are several "bypass" methods out there for mouse movements. I hope to test a few and release it with the next update.
