### ISSUE TITLE
How do I fix this error when select model ?

### ISSUE THREAD

**Issue by ahhtuansz** [Babyhamsta/Aimmy#78]
it keeps showing this and i don't know how to fix it 
![Aimmy 11_23_2023 9_28_39 PM](https://github.com/Babyhamsta/Aimmy/assets/123877525/e49b1e0b-fd6e-408e-8f2c-5fc492b04d6d)

**Comment by vxzl** [comment]
Check if you have the **DirectML.dll** and **onnxruntime.dll** in the same folder as the **.exe**.

**Comment by ahhtuansz** [comment]
> Check if you have the **DirectML.dll** and **onnxruntime.dll** in the same folder as the **.exe**.
> 
> 
> 
> 

yes they're in the same folder

**Comment by Babyhamsta** [comment]
I've been researching this and it may be due to integrated and gpu graphics on the machine. 
Ensure you have the latest DirectX downloaded: https://www.microsoft.com/en-us/download/details.aspx?id=35
