### ISSUE TITLE
error when selecting the models

### ISSUE THREAD

**Issue by howtoinstall26** [Babyhamsta/Aimmy#79]
it keeps crashing with this pop up
![image](https://github.com/Babyhamsta/Aimmy/assets/143302099/c6554ad0-e130-4046-b887-c74e45749ef4)

**Comment by vxzl** [comment]
Check if you have the **DirectML.dll** and **onnxruntime.dll** in the same folder as the **.exe**.

**Comment by howtoinstall26** [comment]
so do i have to move it?

**Comment by fastvariable** [comment]
> Check if you have the **DirectML.dll** and **onnxruntime.dll** in the same folder as the **.exe**.

![image](https://github.com/Babyhamsta/Aimmy/assets/130872826/b4b44240-eb31-4bb6-8436-373b7c54c42e)
