### ISSUE TITLE
Error when selecting any model.

### ISSUE THREAD

**Issue by Mouad-scriptz** [Babyhamsta/Aimmy#81]
![image](https://github.com/Babyhamsta/Aimmy/assets/102869034/5559e5cd-25a6-487f-b8d2-716561d0a482)
I get this error everytime i try to select a model.

Platform: Windows 10 PRO
Processor: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Ram: 8GB

**Comment by vxzl** [comment]
Check if you have all the accquired DLL's:

**DirectML.dll**
**onnxruntime.dll**
- in the same folder as the **.exe**

**Comment by Seconb** [comment]
vxzl is probably right on this

if you notice the .dll files are missing then that probably means your anti-virus falsely flagged them and you should either exclude the Aimmy folder from being searched by your antivirus or disable your antivirus entirely.

also u should share ur gpu, with a i7-3770 i can tell your gpu is probably also weak and wont run Aimmy very well
