### ISSUE TITLE
Error when pressing or selecting on any model it crashes ui 

### ISSUE THREAD

**Issue by Alhasheml** [Babyhamsta/Aimmy#84]
![image](https://github.com/Babyhamsta/Aimmy/assets/137985683/becf3aed-74de-443e-9d50-98048c6e9d42)

**Comment by Babyhamsta** [comment]
Ensure all the dlls are in the same folder as the EXE:

DirectML.dll
onnxruntime.dll

**Comment by ShAdYShmr** [comment]
![image](https://github.com/Babyhamsta/Aimmy/assets/69981718/063cb53f-203e-4b8f-8719-5a122fab92db)
same not working

**Comment by behrad1234** [comment]
same issue
