### ISSUE TITLE
[Suggestion] Configs error after updating from 1.2.0 to 1.3.0

### ISSUE THREAD

**Issue by TomerGamerTV** [Babyhamsta/Aimmy#88]
After updating from 1.2.0 to 1.3.0 the program throws an error saying there is no configs folder in /bin/configs.
Why not just make one?

This is more of a suggestion than an issue because I did fix it but I think there is a better way of doing this.

**Comment by Babyhamsta** [comment]
Fixes have been added to auto create the folders. All old configs no longer work in the newest versions of Aimmy.
