### ISSUE TITLE
My aim isn't locking on the enemy

### ISSUE THREAD

**Issue by intheworlditsgone** [Babyhamsta/Aimmy#89]
Whenever I use the Phantom_Forces_Hamsta model, It never allows me to aim on the enemy and it actively tries to distance itself from the enemies's hitbox. Changing the default settings doesn't fix this.

**Comment by intheworlditsgone** [comment]
Also, whether it does this seems to be specific on what display Phantom Forces is running.

**Comment by Babyhamsta** [comment]
If it is flicking off enemies it means your mouse sensitivity is too low in Aimmy, try a high number like 0.99 and move down from there until you get to a place you like.
