### ISSUE TITLE
[REQUEST] Third person support

### ISSUE THREAD

**Issue by nnesttt** [Babyhamsta/Aimmy#9]
I really like how the aim improves the more you use it, and it starts to learn more as you play. However, it would be really cool if you added third-person support because the aimbot doesn't work very well in third person. For example, in the game Blox Fruits, when you reach level 700 and acquire something called Observation Haki, it provides a 'wallhack,' making it easier for the aimbot to detect targets since the players are highlighted.
![ccb88541-22f2-430a-91b2-33ef7c9cf318](https://github.com/MarsQQ/Aimmy/assets/148981025/1b70cf4a-d9da-49ac-a916-20543a3c09d8)

**Comment by Babyhamsta** [comment]
The AI currently doesn't improve while you play, might just be placebo. We are looking into adding 3rd person support as well, I know we have a few UI updates coming soon and after that I might do a few code clean ups and feature adds like 3rd person.
