### ISSUE TITLE
Missing backend fallback

### ISSUE THREAD

**Issue by SlowPotato** [Babyhamsta/Aimmy#98]
Okay so i followed all steps and I'm on the last step... When i try to do the "training" using - yolo task=detect mode=train imgsz=640 data=data.yaml epochs=100 batch=16 name=filename

I get a lot of errors saying I'm missing [backend fallback]

Need help!
![tester](https://github.com/Babyhamsta/Aimmy/assets/152599873/ff72316f-226a-4b60-b070-718ce26b4fa7)

**Comment by Babyhamsta** [comment]
We don't offer support for YOLO issues. Please open a ticket on the YOLO github.

Thanks
- Hamsta
